[package]
name = "fiapo"
authors = ["uiriansan@github"]
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
gtk4 = { version = "0.10.0", features = ["v4_6", "v4_10"] }
image = "0.25.6"
pdf2image = "0.1.3"
sqlite = "0.37.0"
